### ISSUE TITLE
Reset game issue 

### ISSUE THREAD

**Issue by SoyGema** [deadzombie2333/Minigame_Predict_Battle_Outcome#2]
Ey jin!
First of all, congratulate you for this mini-game evolution.
I am actually learning a lot about your scripting and you deserve all kudos !!

This issue is due to a situation that appears when you execute the mini game from console (not the editor) it seems that it reset the game conditions and then restart
I have been searching for it in **reset** script but I couldn't find it .

This is the video of the situation ( please, once you see tell me so I can put it offline ) 
https://www.youtube.com/watch?v=54Aw_8g2M6o&feature=youtu.be

Note that it happens all the times 
Thanks again for this amazing work in progress

**Comment by deadzombie2333** [comment]
Got it. I'll try launch it from console and see what's going on with it.
